//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arquivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arquivo()
        {
            this.EmailAnexos = new HashSet<EmailAnexo>();
        }
    
        public string Id { get; set; }
        public long Identidade { get; set; }
        public string EntidadeId { get; set; }
        public string ChaveEntidadeId { get; set; }
        public string Nome { get; set; }
        public int Tamanho { get; set; }
        public string Extensao { get; set; }
        public string Diretorio { get; set; }
        public System.DateTime CriadoEm { get; set; }
        public string CriadoPor { get; set; }
        public bool Ativo { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Entidade Entidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailAnexo> EmailAnexos { get; set; }
    }
}
