//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atendimento()
        {
            this.AtendimentoInteracoes = new HashSet<AtendimentoInteracao>();
            this.Clientes = new HashSet<Cliente>();
            this.Ocorrencias = new HashSet<Ocorrencia>();
            this.Telefones = new HashSet<Telefone>();
        }
    
        public string Id { get; set; }
        public long Identidade { get; set; }
        public string CanalId { get; set; }
        public string Protocolo { get; set; }
        public string ClassificacaoId { get; set; }
        public Nullable<int> CampanhaId { get; set; }
        public Nullable<int> MidiaId { get; set; }
        public System.DateTime CriadoEm { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> FinalizadoEm { get; set; }
        public string FinalizadoPor { get; set; }
        public ValidationResult ValidationResult { get; private set; }


        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentoInteracao> AtendimentoInteracoes { get; set; }
        public virtual Canal Canai { get; set; }
        public virtual Classificacao Classificaco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocorrencia> Ocorrencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefone> Telefones { get; set; }
    }
}
