//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class Atividade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atividade()
        {
            this.Anotacoes = new HashSet<Anotacao>();
            this.AtendimentoInteracoes = new HashSet<AtendimentoInteracao>();
            this.Emails = new HashSet<Email>();
            this.FilaAtividades = new HashSet<FilaAtividade>();
            this.Ligacoes = new HashSet<Ligacao>();
            this.Tarefas = new HashSet<Tarefa>();
        }
    
        public string Id { get; set; }
        public long Identidade { get; set; }
        public string AtividadeTipoId { get; set; }
        public string CanalId { get; set; }
        public string ClassificacaoId { get; set; }
        public string ClienteId { get; set; }
        public string OcorrenciaId { get; set; }
        public string AtendimentoId { get; set; }
        public string AtividadeDeOrigemId { get; set; }
        public System.DateTime CriadoEm { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> PrevisaoAtendimento { get; set; }
        public Nullable<System.DateTime> PrevisaoFinalizar { get; set; }
        public Nullable<System.DateTime> IniciadoEm { get; set; }
        public string IniciadoPor { get; set; }
        public Nullable<System.DateTime> FinalizadoEm { get; set; }
        public string FinalizadoPor { get; set; }
        public bool Ativo { get; set; }
        public ValidationResult ValidationResult { get; private set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anotacao> Anotacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtendimentoInteracao> AtendimentoInteracoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Emails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilaAtividade> FilaAtividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligacao> Ligacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarefa> Tarefas { get; set; }
    }
}
