//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SUACC.Dominio.Validacoes;
using System;
using System.Collections.Generic;

namespace SUACC.Dominio.Entidades
{
    public partial class Cliente
    {
        public Cliente()
        {
            this.ClienteEnderecos = new HashSet<ClienteEndereco>();
            this.Contratos = new HashSet<Contrato>();
            this.Ligacoes = new HashSet<Ligacao>();
            this.Ocorrencias = new HashSet<Ocorrencia>();
            this.Telefones = new HashSet<Telefone>();
        }

        public string Id { get; set; }
        public long Identidade { get; set; }
        public string TipoEntidadeCampoValoresId { get; set; }
        public string ClassificacaoId { get; set; }
        public string Documento { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public DateTime? Data { get; set; }
        public bool AceitaComunicados { get; set; }
        public string CanalComunicadosEntidadeCampoValoresId { get; set; }
        public string AtendimentoId { get; set; }
        public DateTime CriadoEm { get; set; }
        public string CriadoPor { get; set; }
        public DateTime? AtualizadoEm { get; set; }
        public string AtualizadoPor { get; set; }
        public bool Ativo { get; set; }
        public ValidationResult ValidationResult { get; private set; }

        public virtual Atendimento Atendimento { get; set; }
        public virtual Classificacao Classificaco { get; set; }
        public virtual ICollection<ClienteEndereco> ClienteEnderecos { get; set; }
        public virtual EntidadeCampoValor EntidadeCampoValore { get; set; }
        public virtual EntidadeCampoValor EntidadeCampoValore1 { get; set; }
        public virtual ICollection<Contrato> Contratos { get; set; }
        public virtual ICollection<Ligacao> Ligacoes { get; set; }
        public virtual ICollection<Ocorrencia> Ocorrencias { get; set; }
        public virtual ICollection<Telefone> Telefones { get; set; }
    }
}
