//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAnexo
    {
        public string Id { get; set; }
        public long Identidade { get; set; }
        public string EmailId { get; set; }
        public bool Inline { get; set; }
        public string ContentId { get; set; }
        public string ArquivoId { get; set; }
        public bool Ativo { get; set; }
        public ValidationResult ValidationResult { get; private set; }


        public virtual Arquivo Arquivo { get; set; }
        public virtual Email Email { get; set; }
    }
}
