//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class Entidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entidade()
        {
            this.Arquivos = new HashSet<Arquivo>();
            this.EntidadeCampoValores = new HashSet<EntidadeCampoValor>();
            this.EntidadeSecoes = new HashSet<EntidadeSecao>();
        }
    
        public string Id { get; set; }
        public int Identidade { get; set; }
        public string Nome { get; set; }
        public string NomeLogico { get; set; }
        public string Script { get; set; }
        public bool PadraoFerramenta { get; set; }
        public System.DateTime CriadoEm { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> AtualizadoEm { get; set; }
        public string AtualizadoPor { get; set; }
        public bool Ativo { get; set; }
        public ValidationResult ValidationResult { get; private set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arquivo> Arquivos { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadeCampoValor> EntidadeCampoValores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadeSecao> EntidadeSecoes { get; set; }
    }
}
