//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class FilaAtividade
    {
        public string Id { get; set; }
        public long Identidade { get; set; }
        public string AtividadeId { get; set; }
        public string FilaId { get; set; }
        public System.DateTime EntrouEm { get; set; }
        public Nullable<System.DateTime> SaiuEm { get; set; }
        public string SaiuPor { get; set; }
        public bool Ativo { get; set; }
        public ValidationResult ValidationResult { get; private set; }


        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Atividade Atividade { get; set; }
        public virtual Fila Fila { get; set; }
    }
}
