//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Menus1 = new HashSet<Menu>();
        }
    
        public string Id { get; set; }
        public long Identidade { get; set; }
        public string Nome { get; set; }
        public string MenuPaiId { get; set; }
        public string Tipo { get; set; }
        public string TipoAbertura { get; set; }
        public int Ordem { get; set; }
        public string Icone { get; set; }
        public string AreaId { get; set; }
        public string AplicacaoId { get; set; }
        public string FuncionalidadeId { get; set; }
        public string CriadoPor { get; set; }
        public System.DateTime CriadoEm { get; set; }
        public string AtualizadoPor { get; set; }
        public string AtualizadoEm { get; set; }
        public bool Ativo { get; set; }
        public ValidationResult ValidationResult { get; private set; }


        public virtual Anotacao Aplicacao { get; set; }
        public virtual Area Area { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Funcionalidade Funcionalidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus1 { get; set; }
        public virtual Menu Menu1 { get; set; }
    }
}
