//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class Motivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motivo()
        {
            this.Motivos1 = new HashSet<Motivo>();
        }
    
        public string Id { get; set; }
        public long Identidade { get; set; }
        public string Nome { get; set; }
        public string MotivoPaiId { get; set; }
        public string NomeExibicao { get; set; }
        public string EstruturaIds { get; set; }
        public string DependenteMotivoId { get; set; }
        public string EntidadeNomeLogicos { get; set; }
        public string AtividadeTipoIds { get; set; }
        public bool PadraoFerramenta { get; set; }
        public ValidationResult ValidationResult { get; private set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Motivo> Motivos1 { get; set; }
        public virtual Motivo Motivo1 { get; set; }
    }
}
