//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoClassificacao
    {
        public string Id { get; set; }
        public long Identidade { get; set; }
        public string MotivoId { get; set; }
        public string ClassificacaoId { get; set; }
        public bool PadraoFerramenta { get; set; }
        public System.DateTime CriadoEm { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> AtualizadoEm { get; set; }
        public string AtualizadoPor { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public ValidationResult ValidationResult { get; private set; }

    }
}
