//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoClassificacaoFila
    {
        public long Id { get; set; }
        public string MotivoClassificacaoId { get; set; }
        public string FilaId { get; set; }
        public string AtividadeTipoId { get; set; }
        public string MotivoId { get; set; }
        public string ClassificacaoId { get; set; }
        public string EmailModeloId { get; set; }
        public Nullable<int> SlaAtendimento { get; set; }
        public Nullable<int> SlaFechamento { get; set; }
        public System.DateTime CriadoEm { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> AtualizadoEm { get; set; }
        public string AtualizadoPor { get; set; }
        public bool Ativo { get; set; }
        public ValidationResult ValidationResult { get; private set; }

    }
}
