//------------------------------------------------------------------------------
// <auto-generated>
using SUACC.Dominio.Validacoes;
using System;

namespace SUACC.Dominio.Entidades
{   
    public class MotivoClassificacaoFila
    {
        public MotivoClassificacaoFila()
        {
            ValidationResult = new ValidationResult(); 
        }

        public long Id { get; set; }
        public string MotivoClassificacaoId { get; set; }
        public string FilaId { get; set; }
        public int AtividadeTipoId { get; set; }
        public string EmailModeloId { get; set; }
        public int? SlaAtendimento { get; set; }
        public int? SlaFechamento { get; set; }
        public DateTime CriadoEm { get; set; }
        public string CriadoPor { get; set; }
        public DateTime? AtualizadoEm { get; set; }
        public string AtualizadoPor { get; set; }
        public bool Ativo { get; set; }
        public ValidationResult ValidationResult { get; private set; }

    }
}
