//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class Remessa
    {
        public string Id { get; set; }
        public long Identidade { get; set; }
        public string MailingId { get; set; }
        public string StatusEntidadeCampoValoresId { get; set; }
        public int Ordem { get; set; }
        public string NomeArquivo { get; set; }
        public System.DateTime IniciadoEm { get; set; }
        public Nullable<System.DateTime> FinalizadoEm { get; set; }
        public int TotalLinhas { get; set; }
        public string Erro { get; set; }
    
        public virtual EntidadeCampoValor EntidadeCampoValore { get; set; }
        public virtual Mailing Mailing { get; set; }
        public ValidationResult ValidationResult { get; private set; }

    }
}
