//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Telefone()
        {
            this.Ligacoes = new HashSet<Ligacao>();
        }
    
        public string Id { get; set; }
        public long Identidade { get; set; }
        public string ClienteId { get; set; }
        public string AtendimentoId { get; set; }
        public string StatusEntidadeCampoValoresId { get; set; }
        public string TipoEntidadeCampoValoresId { get; set; }
        public Nullable<int> Ddi { get; set; }
        public Nullable<int> Ddd { get; set; }
        public long Numero { get; set; }
        public bool SomenteNumero { get; set; }
        public System.DateTime CriadoEm { get; set; }
        public string CriadoPor { get; set; }
        public ValidationResult ValidationResult { get; private set; }


        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Atendimento Atendimento { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual EntidadeCampoValor EntidadeCampoValore { get; set; }
        public virtual EntidadeCampoValor EntidadeCampoValore1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligacao> Ligacoes { get; set; }
    }
}
