//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public string Id { get; set; }
        public long Identidade { get; set; }
        public Nullable<System.DateTime> UtilizadoEm { get; set; }
        public string Acao { get; set; }
        public string UsuarioId { get; set; }
        public System.DateTime CriadoEm { get; set; }
        public System.DateTime ExpiraEm { get; set; }
        public bool Ativo { get; set; }
        public ValidationResult ValidationResult { get; private set; }


        public virtual AspNetUser AspNetUser { get; set; }
    }
}
