//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUACC.Dominio.Entidades
{
    using SUACC.Dominio.Validacoes;
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioPausa
    {
        public string Id { get; set; }
        public long Identidade { get; set; }
        public string MotivoPausaId { get; set; }
        public string UsuarioId { get; set; }
        public string CanalId { get; set; }
        public System.DateTime IniciadoEm { get; set; }
        public Nullable<System.DateTime> FinalizadoEm { get; set; }
        public bool Expirado { get; set; }
        public ValidationResult ValidationResult { get; private set; }

    }
}
